# ==========================================
# DATASOURCE - CONEXIÓN A NEON.TECH
# ==========================================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# JPA / HIBERNATE - CONFIGURACIÓN
# ==========================================
# Dialecto estándar para PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# IMPORTANTE: 'validate' verifica que tus entidades de Java coincidan con las
# tablas de Neon, pero NO borra ni altera la estructura que acabamos de importar.
#spring.jpa.hibernate.ddl-auto=validate#
spring.jpa.hibernate.ddl-auto=none
# ==========================================
# DEBUG - CONSOLA
# ==========================================
# Muestra las consultas SQL en la consola (muy útil para ver si PostGIS responde bien)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# SERVIDOR
# ==========================================
server.port=8081